### PR TITLE
Various fixes and enhancement for consideration

### PR DESCRIPTION
**Pull request by iv-gha**
Hello Gareth,

Here are some bits to consider. Some are pure fixes. Others apply existing good ideas and behaviours wider.

I do propose subtle changes to the menus to make them easier to understand.  I have been avoiding menus - but have spotted (perhaps) an evolutionary improvement we could make, inspired by the on-screen button groupings.  Of course what I consider helpful...

Happy to discuss my few tweaks.  Hopefully some good things.

Kind regards
Ian

ADDED:

I have now realised the menu change would need a user guide change - work!  It may be that we pull back a bit and keep 'Gestures and Menus' but deal with potential pain points for users.  For example, we could put 'Customise Quick Launch Buttons' as a button on the buttons page and remove it from the menu - no more split of button activities over 2 menus.

### CODE REVIEW

**Comment by thebigg73** [comment]
Hi Ian, I'll take a look shortly.
The menus and app navigation (UI/UX) is the main reason I'm writing the app (material app version) to consolidate menus and make it all a bit tidier and easier to navigate.  Happy to consider changes that are smallish in nature for now, knowing they will be completely different in the rewrite.  I'm slowly working through the menus/options/preferences just now in the new version before I start importing the song features etc.  I'll be pushing a new version of the work completed so far tonight to the MaterialApp branch if you wanted to get an idea of what I'm doing (remember this version isn't usable yet though)

**Comment by iv-gha** [comment]
I have added a few more tweaks to menus - this includes moving 'customising quick launch' to being an button on the 'Page buttons' dialog - seemed logical!

Kind regards
Ian

**Review by thebigg73 — APPROVED** [review]
Looks good on review.  I'll merge the request and test.
Thanks Ian.

**Comment by iv-gha** [comment]
I forgot to mention some 'strings' changes - watch out for those.

Ian

**Comment by iv-gha** [comment]
Have you considered replacing the red X close icon with a > (< for song menu) and the up icon with up facing chevron to move to a more 'blandroid'  look!  A bit like the simple icons seen in Google calendar etc.  If we are going flatter...

Kind regards
Ian

**Pull request merged**
