### PR TITLE
Config refactoring

### PR DESCRIPTION
**Pull request by hohwille**
I had to reintegrate my changes from scratch by deleting my fork and creating it again as there were lots of complex git merge issues. As I had lots of bad experience with git merge issues over multiple repos and branches, I wanted to be cautious and avoid any possible adventures.
So from your repo I created a clean fork today, cloned it, created my feature branch and then copied over my changes to it. I did two commits:
1. commit all the new files that do not interfere with your app at all till the stage of that commit
2. commit that shows a first step how the config should go out of FullscreenActivity into the new config

It is fully functional and tested. However, please carefully review the changes.
I wanted to keep the actual changes in the app minimal for the first PR. So still after 2. only 3% of the code from 1. is actually used. Also moving all configurations from FullscreenActivity to the new config will still be a bigger change. With this PR I wanted to give a preview. You can still decide how to structure the new config (it is hierarchical and groups configuration values rather than having tons of unstructured fields in FullscreenActivity that are also mixed with fields about the current song or current status). Also we could work in parallel on different aspects of the config to split the workload. At least the merge conflicts that broke my local git repo show that going in small steps with faster re-integration is much better than working on a XXL change isolated.

### CODE REVIEW

**Comment by hohwille** [comment]
Just added a 3. commit for travis-ci.

**Comment by thebigg73** [comment]
Many thanks for this.
I'm still testing the changes I've made, but made major progress today.  I will definitely be pulling in your merge request, but I'll wait until I push my changes back to the main branch.  This will help me avoid conflicts with any new changes I've made and allow better testing  
Unless you can guide me on how to pull your changes into my development branch?

**Comment by thebigg73** [comment]
Hi,
I've pushed my changes to the Master branch.  As I've said before, there are pretty major changes.  Most are to do with File access (which is not working properly for post KitKat devices).  File access is now moved to StorageAccess.java which deals with the majority of the file access requests.  Each function has a kitkat version (using old KitKat File code) and lollipop+ version (using newer StorageAccessFramework).  I've also removed some static variables from FullscreenActivity.

Looking at your pull request, there's lots of conflicts now unfortunately as you had been working on the Master which didn't have my changes (which are there now).  What's the best way to proceed with this?

Gareth

**Comment by hohwille** [comment]
Sorry, I have been busy with many other OSS projects meanwhile. I could simply rework this PR to resolve the conflicts for you. However, for the next month I am still very busy. Maybe I will then also bring in a smaller set of additions to make the PR smaller and avoid already adding code that is not clear and confirmed to be ever used.

**Comment by thebigg73** [comment]
Hi Jorg

No worries at all.  I know the busy feeling!  I'm still working on the big
update, but it is nearly ready for the second beta release.  Probably not
going to try to merge your pull requests until I've released the update to
the main branch.  I don't want to cause you extra work either!

Gareth

**Comment by hohwille** [comment]
OK. I already invested some time to reintegrate my changes. After reverting almost every of my change to your existing code, I started the APP and got this:
Screenshot 2019-06-05 at 23 04 05
So it seems you are still in a "Work in Progress" state?
Let me know when time is right to do the changes...

**Comment by thebigg73** [comment]
Hi,

I've updated the master now with the most up to date beta version of the app.  I'm hoping that there will only now be minor changes to the app when I release to production on the Play Store.
What's the best way to proceed with your changes?  I suspect that there will be lots of conflicts!

Gareth

**Pull request closed without merging**
