### PR TITLE
Fixes: Import and Export fixes

### PR DESCRIPTION
**Pull request by iv-gha**
URGENT Fix - ReceivedSong mechanism fix.
Export - Fix for failure to ignore extra information sections.
Import: Fix for failing import if file at the root of drive.

### CODE REVIEW

**Comment by iv-gha** [comment]
Hello Gareth,

I hope things are progressing well. 

A few fixes - few lines affected.

Is edit of chords OK?

It looks like you are happy.

Kind regards
Ian V

**Comment by thebigg73** [comment]
Hi Ian,

I tried the chords again and looks good.  Don't know what happened when I
tested it.  It might have been on a device with an older version!  I'll add
those fixes later today.

Cheers,
Gareth

**Comment by iv-gha** [comment]
Sounds good.

Testing...

I still have not seen the 'receive songs' mode of 'connect' working.
So
host:
act as host on
Enable nearby connections on
Receive host songs off
Keep host songs off

Client
act as host off
Enable nearby connections on
Receive host songs on
Keep host songs off

For a song on host but not on client I get the not on device message on
client. I would expect received file and display?

Set client to Keep host songs and as expected it creates the file on the
client.

All running 5.2.0.

Am I testing this wrong?

Kind regards
Ian V

**Comment by thebigg73** [comment]
No, sounds like you're set up properly.  If you receive host songs (but not
keep them), the app on the client should create a temporary copy in the
Received folder (song will be called ReceivedSong).  Every song sent will
be bored in this way.  I'll check it out tonight.

Gareth

**Comment by thebigg73** [comment]
Can you confirm if the host songs are in the main folder or subfolder, or
does it not work regardless?

**Comment by iv-gha** [comment]
Hello Gareth,

It was a main song.  I then created a new main song and tried (definitly
did not exist on client!) and that failed.  The received folder gets the
file as I Looked, so that bit works - but it is not displayed just the
error.  A thought - has the file handling changed? I had to tweak import
names recently.

Kind regards
Ian

**Comment by iv-gha** [comment]
Hello Gareth,

I have had a look and a slight code re-org fixes...  I have pushed to my branch.

Kind regards
Ian V

**Comment by thebigg73** [comment]
Hi Ian,
I've merged everything other than NearbyConnections - I'd got a fix already, but it also dealt with other issues, so I didn't include your version of that file.

**Comment by iv-gha** [comment]
No problem. I will take a look at nearby stuff.
Knd regards
Ian V

**Pull request merged**
