### PR TITLE
Major update to Nearby section change handling

### PR DESCRIPTION
**Pull request by iv-gha**
Hello Gareth,

A host sending section changes and a client using section changes are kept in better step - important for 'Stage' controlling 'Presentation'.

I did not want to throw out first and last song (with delay) being sent to clients during rapid song changes  This handles section changes in the delay period - previously changing the clients old song and not being applied to the new song!  Sorted.

I think I need a rest!

Kind regards
Ian

### CODE REVIEW

**Comment by thebigg73** [comment]
You have been busy!!  I'll get a look shortly - work at the day job has
been chaotic just now and I've been struggling to make time to get a
serious look at your (likely excellent) work.  Trust me, I really
appreciate your input with this!
Gareth

**Review by thebigg73 — APPROVED** [review]
Pulled in!  Look good - I've not manuallly copied in the stage mode sections work yet to MaterialApp as that is currently non-existent!  I'll need to try to remember!

**Comment by iv-gha** [comment]
Great. I think I have found all of the rabbit holes that PDF and Image
handling go to!  Have fun.

**Comment by iv-gha** [comment]
Hello Gareth,  just a note about nearby...  If 'receive host songs' is off on a client then only BYTE info is used and the FILE transfers are cancelled.  This makes all song types fast on the client, all use BYTE and local songs.  Before this change songs with FILE would not be progressed until the (unused) FILE completed.  A client will also cancel older transfers when a new song arrives.  Previously old FILE transfer continued resulting in an unneeded song being displayed.  Cancel is very good!

**Pull request merged**
