### PR TITLE
HOTFIX: Correction following further testing - lollipopCreateFileForOutputStream

### PR DESCRIPTION
**Pull request by iv-gha**
… must not delete an existing folder

DO NOT TEST #148.
APPLY #149 BEFORE TESTING - #148 is bugged, this is a fix of 'emptying of folders' found following further testing!  Apologies.

Added null handling

Kind regards
Ian

### CODE REVIEW

**Comment by iv-gha** [comment]
IMPORTANT - DO NOT TEST  #148, APPLY #149 BEFORE TESTING

**Review by thebigg73 — APPROVED** [review]
Good spot Ian - I've been really busy the last week and hadn't tried testing the previous pull request!
I'll try to get this pushed as a new update soon (and test!)

**Comment by iv-gha** [comment]
Hello Gareth,

Found the root cause of the set folder empty - great.  Load a set, close app, open app. save set.  In this situation StaticVariables.settoload  was not set giving an empty filename, this resulted in 'file' code (delete and create) running against the folder.  I have adjusted set and 'file' code.

I think later we need to separate file and folder creation calls - making the code more obvious and (with appropriate parameter validation) perhaps safer.

Kind regards
Ian

**Comment by iv-gha** [comment]
Hello Gareth,

Saw Alistair's comments re Highlighter delete/save/cancel behaviour.  Put a commit forward to make behaviour more intuitive - I hope.  Alistair seems to have been a supporter of the project from the start - respect.

Cheers
Ian

p.s. The comment on the commit should have contained 'Save logic will exit with a file existing only if a drawing was present.'

**Pull request merged**
