### PR TITLE
Fix: Crash fix - 'makeVariation'

### PR DESCRIPTION
**Pull request by iv-gha**
Found a crash!

### CODE REVIEW

**Comment by iv-gha** [comment]
Hi Gareth,

Ability to add song quickly to a set as a variation using long press of '+'...

So on a Sunday meet, I have a set to share with projectionist and other musicians / singers.  We all connect.  They create a new set and connect to receive my songs (no keep).   Once connected, I step through my songs, they long press '+' to add them to their set.  At the end they all have a set in the correct order of variations with these being my songs (my key, my ordering, etc) with no effect on their own song library.  Done with long press '+' actions.

If during performance connection issues occur then everyone has my songs in a set to use.  Safe!

I could have prepared and shared a set of variations to get this, but that is painful and for many leaders a seemingly big ask!  The above is dynamic allowing any OSA user to collect the leaders set (with any last minute changes, different keys, different order etc) on the fly.  It has no need for sync of songs, use of email etc - Just OSA.

I think Material would not as easily support this yet.

Hence the fix to keep my Master friends happy and able to do this!

**Comment by thebigg73** [comment]
As if I'd forget about your amazing contributions.....

I've added a page button.  Short press=add to set, long press=add to set as
a variation.

[image: addtosetbutton.png]
[image: addtosetvariation2.png][image: addtosetvariation3.png]

**Comment by iv-gha** [comment]
Sounds good.  This fix needs test and release as '+' long press is broken in 'Master'.

Cheers

**Review by thebigg73 — APPROVED** [review]
Thanks!

**Pull request merged**
