### PR TITLE
Added ukrainian translation

### PR DESCRIPTION
**Pull request by ktarasz**

### CODE REVIEW

**Comment by ktarasz** [comment]
Hello 
I want add new translation for Ukrainian language (https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=uk)
I'm not sure that is full changes for this.  Please keep me know if you need something else... 
Thanks

**Comment by ktarasz** [comment]
@thebigg73 Any updates?

**Comment by thebigg73** [comment]
Hi there,

Thanks for this.  I'm currently away from my computer just now (getting an
operation), so haven't checked it properly.  On first glance though, it
looks fine.  Many thanks for taking the time to do this.  All going well,
it'll be in the next release!

Gareth

**Review by thebigg73 — APPROVED** [review]
I'll pull this request and test.  Looks fine on first glance, but might need some updated translations if you're up for it.  I'll also add the option to select this translation from the appropriate UI page.

**Comment by thebigg73** [comment]
I've tested this and made a few minor changes (apostrophes ' should be escaped \' and some end of string tags weren't being recognised properly < / string> rather than </string>
Also updated the PopUpLanguage fragment and list of available languages to choose from (in 
English string.xml as untranslatable).

This will be added to the next release on the Play Store (a few other bits to fix for me first though!).
Many thanks for contributing!

**Comment by thebigg73** [comment]
I've pushed your translation to the Google Play store beta channel (https://play.google.com/apps/testing/com.garethevans.church.opensongtablet).  Only users subscribed to the beta channel updates will get access to this for now.  Once it has passed testing (it's not your contribution that will be the issue, but other updates I've added!), I'll push it to the stable channel release for everyone to access the update.

Many thanks again Tarasz

**Pull request merged**
