### PR TITLE
updated autoscroll features and directory list

### PR DESCRIPTION
**Pull request by millerthegorilla**
I've added two quicklaunch buttons to increase and decrease the speed of the autoscroll.

I've added a text field in the autoscroll delay time that allows the max delay time to be increased.

I've added directory links in the song list, so that it is possible to navigate more easily, and so that directories with only subdirectories and no songs have something to display.

I've updated the search index to have the recursively generated folder list included.  This allows search and random song generation to work.

So far it seems to work ok, but I'd like to take another look at the autoscroll, to make the adjustment of the autoscroll easier, by switching it off whilst the song is manually scrolled up and down, and then switching it back on again.  I also want to add a stop autoscroll button to the quicklaunch next.

### CODE REVIEW

**Comment by millerthegorilla** [comment]
I've just recalled, I've left a memory leak tool in the code, and need to remove it, but won't be able to do it until tomorrow am.

**Comment by millerthegorilla** [comment]
I've finished this and tested it a little - it all seems to work ok.  I've added a couple of quicklaunch autoscroll buttons.

**Comment by millerthegorilla** [comment]
There are still issues with this code so please hold any merge.  I have just noticed that the menu touch and the menu item is out of sync, I'll have a look tomorrow.

**Comment by thebigg73** [comment]
No problem.  I'm currently rebuilding my development laptop as the hard
drive had begun to fail.  Not quite fit everything back up and running yet!

**Comment by millerthegorilla** [comment]
Ok, I've finished fixing the errors.  As usual I've tested as much as I can, but I don't use the presentation mode so much or the slides etc.  I've stuck to the API so it should be fine though.
I've added some error info to the log that the user can see.
That's about all I need it to do at the moment.  It's great that its working, quite an achievement, such a large and functional code base for one person who professes to be learning - the reason I mention this, is that I quite fancy doing some refactoring of a serious nature, I'd like to rewrite it from scratch actually, keeping the functionality and the look, but writing it to OOP standards.  This will leave a better and more functional code base for the future and will involve far better memory management amongst other benefits.  However, I'm snowed under at the moment with life event managements of a sort, so I won't be able to begin in the immediate future.
Many thanks though for providing the code opensource, and if there's anything wrong with what I've done, or anything that you need any help with then let me know!
Cheers.

**Comment by thebigg73** [comment]
Ok, merged the pull request and made some fixes and changes (see the commit log)
Struggling to get the folders in the song menu to properly sort alphabetically above the songs.  Always seems to revert back to reverse alphabetical order for the folders.  Any clues?

**Pull request merged**
